### ISSUE TITLE
List is outdated

### ISSUE THREAD

**Issue by bobatsar** [fieldnotescommunities/ios-device-identifiers#18]
Hi there,

it seems your list is outdated.

Could you update with the contents from
https://gist.github.com/adamawolf/3048717

Thanks

**Comment by bobatsar** [comment]
See my PR #19

**Comment by timdiggins** [comment]
Hey thanks @bobatsar - any chance you can give me a PR with the additions, rather than changing the previous data (which was well researched by @pschmidtboeing and myself and represents useful or more accurate data).  If you don't want to, no sweat I can update, just let me know.

**Comment by bobatsar** [comment]
Ok updated with PR #20

**Comment by timdiggins** [comment]
Thanks! merged.
